apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extension-traefik.fullname" . }}
  labels:
  {{- include "extension-traefik.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
