on:
  push:
    branches:
      - main
    # paths:
    #   - suffiks/**

jobs:
  build-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: "Build and release charts"
        uses: ./.github/actions/release
        with:
          directory: suffiks
          remote: oci://ghcr.io/suffiks/charts
          password: ${{ secrets.GITHUB_TOKEN }}
