on:
  push:
    branches:
      - main
    paths:
      - suffiks/**
  workflow_dispatch:

jobs:
  build-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: "Build and release charts"
        uses: ./.github/actions/release
        with:
          directory: suffiks
          password: ${{ secrets.GITHUB_TOKEN }}
