apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suffiks.fullname" . }}
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
data:
  config.yaml: |
    apiVersion: suffiks.com/v1
    kind: ProjectConfig
{{ toYaml .Values.config | indent 4 }}
