apiVersion: v1
kind: Service
metadata:
  name: {{ include "suffiks.fullname" . }}-docs
  labels:
    {{- include "suffiks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.docService.type }}
  selector:
    {{- include "suffiks.selectorLabels" . | nindent 4 }}
  ports:
	  {{- .Values.docService.ports | toYaml | nindent 4 -}}
