apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "suffiks.fullname" . }}-serving-cert
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "suffiks.fullname" . }}-webhook.{{ .Release.Namespace }}.svc'
  - '{{ include "suffiks.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "suffiks.fullname" . }}-selfsigned-issuer'
  secretName: {{ include "suffiks.fullname" . }}-wh-cert
