apiVersion: v1
kind: Service
metadata:
  name: {{ include "suffiks.fullname" . }}-webhook
  labels:
  {{- include "suffiks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    {{- include "suffiks.selectorLabels" . | nindent 4 }}
  ports:
	  {{- .Values.webhookService.ports | toYaml | nindent 4 -}}
